from flask import Flask, jsonify, render_template

app = Flask(__name__)

PRODUCTS = [
    {
        "id": "lakshmi-haram",
        "name": "లక్ష్మీ హారం",
        "category": "హారాలు",
        "tag": "తెలంగాణ ప్రత్యేకం",
        "short_description": "తెలంగాణ పెళ్లిళ్లలో ప్రత్యేకంగా ధరించే లక్ష్మీ దేవి నాణేల హారం.",
        "description": "లక్ష్మీ దేవి రూపాలతో రూపొందించిన ఈ సంప్రదాయ హారం పట్టు చీరలతో ఎంతో అందంగా కనిపిస్తుంది.",
        "image": "/static/images/lakshmi-haram.jpg",
        "price": 397090,
        "weight": "24.80 g",
        "carat": "22 క్యారెట్లు (916)",
        "gold_rate": 342840,
        "making_charge": 8400,
        "making_percent": 9.5,
        "wastage_percent": 12,
        "wastage_value": 34284,
        "stones": "క్యూబిక్ జిర్కోనియా అలంకరణ",
        "occasion": "పండుగలు / వివాహాలు",
        "delivery": "7-10 పని దినాలు",
    },
    {
        "id": "telangana-buttalu",
        "name": "తెలంగాణ బుట్టలు",
        "category": "చెవి ఆభరణాలు",
        "tag": "అందరి అభిమానం",
        "short_description": "తెలంగాణ సంప్రదాయ శైలిలో ముత్యాల వేలాడే బుట్ట చెవిదిద్దులు.",
        "description": "చెవులకు తేలికగా ఉండేలా రూపొందించిన ఈ బుట్టలు చిన్న గంటల అలంకరణతో కదలికలో మెరుస్తాయి.",
        "image": "/static/images/telangana-buttalu.jpg",
        "price": 74200,
        "weight": "9.60 g",
        "carat": "22 క్యారెట్లు (916)",
        "gold_rate": 6450,
        "making_charge": 6100,
        "making_percent": 9.9,
        "wastage_percent": 10,
        "wastage_value": 6192,
        "stones": "రాళ్లు లేవు",
        "occasion": "రోజువారీ / పండుగలు",
        "delivery": "5-7 పని దినాలు",
    },
    {
        "id": "vanki-bajuband",
        "name": "వంకి బాజుబంద్",
        "category": "వివాహ ఆభరణాలు",
        "tag": "కొత్త డిజైన్",
        "short_description": "తెలంగాణ వధువుల సంప్రదాయ వంకి ఆకారంలో అందమైన బాజుబంద్.",
        "description": "చేతి పైభాగంలో అందమైన వంపును సృష్టించే ఈ వంకి, పెళ్లి నగలతో సహజంగా కలిసిపోతుంది.",
        "image": "/static/images/vanki-bajuband.jpg",
        "price": 116800,
        "weight": "15.35 g",
        "carat": "22 క్యారెట్లు (916)",
        "gold_rate": 6450,
        "making_charge": 8900,
        "making_percent": 9.0,
        "wastage_percent": 11,
        "wastage_value": 10909,
        "stones": "తెల్ల జిర్కోనియా రాళ్లు",
        "occasion": "రోజువారీ ప్రత్యేకత",
        "delivery": "6-8 పని దినాలు",
    },
    {
        "id": "gold-gajulu",
        "name": "సాదా బంగారు గాజులు",
        "category": "గాజులు",
        "tag": "కాలాతీతం",
        "short_description": "తెలంగాణ ఇళ్లలో ప్రతిరోజూ ధరించే మెత్తని అంచుల సాదా గాజులు.",
        "description": "ఒంటరిగా లేదా ఇతర గాజులతో కలిపి ధరించడానికి అనువైన ఈ గాజులు ప్రతి సందర్భానికీ సరిపోతాయి.",
        "image": "/static/images/gold-gajulu.jpg",
        "price": 38600,
        "weight": "5.15 g",
        "carat": "22 క్యారెట్లు (916)",
        "gold_rate": 5280,
        "making_charge": 4200,
        "making_percent": 11.7,
        "wastage_percent": 8,
        "wastage_value": 2177,
        "stones": "సాదా బంగారు మెరుగు",
        "occasion": "బహుమతి / రోజువారీ",
        "delivery": "4-6 పని దినాలు",
    },
    {
        "id": "nalla-poosala-haram",
        "name": "నల్లపూసల హారం",
        "category": "మంగళసూత్రాలు",
        "tag": "సంప్రదాయం",
        "short_description": "తెలంగాణ వివాహ సంప్రదాయానికి గుర్తుగా నల్లపూసలతో రూపొందించిన హారం.",
        "description": "బంగారు పూసలు మరియు నల్లపూసల సమతుల్య కలయికతో రూపొందించిన ఈ హారం రోజువారీ ధరించడానికి సౌకర్యంగా ఉంటుంది.",
        "image": "/static/images/nalla-poosala-haram.jpg",
        "price": 51200,
        "weight": "6.90 g",
        "carat": "22 క్యారెట్లు (916)",
        "gold_rate": 6450,
        "making_charge": 4600,
        "making_percent": 10.3,
        "wastage_percent": 9,
        "wastage_value": 4000,
        "stones": "నల్లపూసలు, బంగారు పూసలు",
        "occasion": "వివాహం / రోజువారీ",
        "delivery": "5-7 పని దినాలు",
    },
    {
        "id": "kasula-haram",
        "name": "కాసుల హారం",
        "category": "వధువు నగలు",
        "tag": "వధువు ఎంపిక",
        "short_description": "తెలంగాణ పెళ్లిళ్లలో ప్రియమైన నాణేలతో రూపొందించిన అద్భుతమైన కాసుల హారం.",
        "description": "ప్రతి కాసుపై సంప్రదాయ లక్ష్మీ రూపంతో, వధువు అలంకరణకు వైభవాన్ని చేర్చే ప్రత్యేక హారం.",
        "image": "/static/images/kasula-haram.jpg",
        "price": 158900,
        "weight": "20.40 g",
        "carat": "22 క్యారెట్లు (916)",
        "gold_rate": 6450,
        "making_charge": 12800,
        "making_percent": 9.7,
        "wastage_percent": 13,
        "wastage_value": 17169,
        "stones": "లక్ష్మీ రూపాల నాణేలు",
        "occasion": "వివాహం / వేడుకలు",
        "delivery": "10-14 పని దినాలు",
    },
]


@app.get("/")
def home():
    return render_template("index.html")


@app.get("/api/products")
def products():
    return jsonify(PRODUCTS)


if __name__ == "__main__":
    app.run(debug=True, host="127.0.0.1", port=5000)
